#!/usr/bin/env python3
"""Generate a static manifest.js so the gallery works fully offline.

Run this whenever you add/rename/remove folders or images:

    python3 generate_manifest.py

It scans every top-level folder for image files and writes `manifest.js`,
which the page loads via a <script> tag. Because it's a plain script (not a
fetch), the gallery works by just opening index.html directly - no server
needed. Zip the whole folder and your friend can open index.html offline.
"""

import json
import os
import re

IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp", ".gif"}


def natural_key(name):
    """Sort filenames so 2.PNG comes before 10.PNG."""
    return [int(t) if t.isdigit() else t.lower() for t in re.split(r"(\d+)", name)]


def build_manifest(root):
    folders = []
    for entry in sorted(os.scandir(root), key=lambda e: natural_key(e.name)):
        if not entry.is_dir() or entry.name.startswith("."):
            continue
        images = [
            f.name
            for f in os.scandir(entry.path)
            if f.is_file() and os.path.splitext(f.name)[1].lower() in IMAGE_EXTENSIONS
        ]
        if not images:
            continue
        images.sort(key=natural_key)
        folders.append({"name": entry.name, "images": images})
    return {"folders": folders}


def main():
    root = os.path.dirname(os.path.abspath(__file__))
    manifest = build_manifest(root)
    payload = json.dumps(manifest, indent=2, ensure_ascii=False)
    out = os.path.join(root, "manifest.js")
    with open(out, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by generate_manifest.py - do not edit by hand.\n")
        f.write("window.FLOW_MANIFEST = " + payload + ";\n")
    total = sum(len(f["images"]) for f in manifest["folders"])
    print(f"Wrote manifest.js: {len(manifest['folders'])} folders, {total} images.")


if __name__ == "__main__":
    main()
